import {
  SwiperImg as SwiperImgMP,
  SwiperCategory as SwiperCategoryMP,
} from './component/swiper'
import LocalStorage from './storage'
import MapMP from './component/map'
import StatusBarMP from './component/status_bar'
import SafeHeaderMP from './component/safe_header'

import useFirstDidShow from './hook/use_first_did_show'

import {
  // 不提供，请用 PageMP
  // LayoutRoot,
  // Page,
  Button,
  ButtonTime,
  Flex,
  Loading,
  Mask,
  Text,
  Toast,
  View,
  Label,
  Tabs,
  Badge,
  Switch,
  TagWrap,
  Square,
  RangeCalendar,
  MultipleCalendar,
  Calendar,
  Dialog,
  Checkbox,
  Radio,
  Divider,
  Popup,
  Tooltip,
  ActionSheet,
  Search,
  FakeSearch,
  SearchPage,
  InnerLayer,
  Input,
  InputMaxLength,
  InputPassword,
  Textarea,
  Cells,
  Cell,
  CellForm,
  CellsForm,
  Picker,
  CouplingPicker,
  ConfirmPicker,
  ConfirmCouplingPicker,
  SelectPicker,
  RepeatTimes,
  Price,
  Nav,
  VList,
  Status,
} from '@gm-mobile/c-react'

export {
  // 不提供，请用 PageMP
  // LayoutRoot,
  // Page,
  Button,
  ButtonTime,
  Flex,
  Loading,
  Mask,
  Text,
  Toast,
  View,
  Label,
  Tabs,
  Badge,
  Switch,
  TagWrap,
  Square,
  RangeCalendar,
  MultipleCalendar,
  Calendar,
  Dialog,
  Checkbox,
  Radio,
  Divider,
  Popup,
  Tooltip,
  ActionSheet,
  Search,
  FakeSearch,
  SearchPage,
  InnerLayer,
  Input,
  InputMaxLength,
  InputPassword,
  Textarea,
  Cells,
  Cell,
  CellForm,
  CellsForm,
  Picker,
  CouplingPicker,
  ConfirmPicker,
  ConfirmCouplingPicker,
  SelectPicker,
  RepeatTimes,
  LocalStorage,
  Price,
  Nav,
  VList,
  Status,
  SwiperImgMP,
  SwiperCategoryMP,
  MapMP,
  StatusBarMP,
  SafeHeaderMP,
  useFirstDidShow,
}

export * from './component/image'
export * from './component/page'
export * from './component/counter'
